---
# handlers file for ansible_role_nginx
- name: Restart server
  ansible.builtin.service:
    name: nginx
    state: restarted
  become: true
- name: Enabled server
  ansible.builtin.service:
    name: nginx
    enabled: true
  become: true
- name: Start server
  ansible.builtin.service:
    name: nginx
    state: started
  become: true